# Generated by Django 3.0.8 on 2020-07-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('end_time', models.DateTimeField(null=True, verbose_name='dedline')),
                ('start_time', models.DateTimeField(null=True, verbose_name='start time')),
                ('working_time', models.DateTimeField(null=True, verbose_name='start time')),
                ('time_needed', models.DateTimeField(null=True, verbose_name='start time')),
                ('rate', models.IntegerField(default=1)),
            ],
        ),
    ]
