# Generated by Django 3.0.8 on 2020-07-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_done', models.BooleanField(default=False)),
                ('period', models.CharField(default='n', max_length=1)),
                ('multi_change', models.BooleanField(default=False)),
                ('time_needed', models.TimeField(null=True, verbose_name='time needed')),
                ('working_time', models.DateTimeField(null=True, verbose_name='working time')),
                ('end_time', models.DateTimeField(null=True, verbose_name='dedline')),
                ('start_time', models.DateTimeField(null=True, verbose_name='start time')),
                ('rate', models.IntegerField(default=1)),
            ],
        ),
    ]
