# Generated by Django 3.0.8 on 2020-07-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='period',
            field=models.CharField(default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_needed',
            field=models.DateTimeField(null=True, verbose_name='time needed'),
        ),
        migrations.AlterField(
            model_name='task',
            name='working_time',
            field=models.DateTimeField(null=True, verbose_name='working time'),
        ),
    ]
