# Generated by Django 3.0.8 on 2020-07-28 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('to_do_number', models.IntegerField(default=0)),
                ('done_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='cost_of_delay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='delay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='punishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.Punishment'),
        ),
    ]
