# Generated by Django 3.0.8 on 2020-07-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20200716_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_needed',
            field=models.TimeField(null=True, verbose_name='time needed'),
        ),
    ]
