# Generated by Django 3.0.8 on 2020-07-16 20:40

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20200716_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='delivery_date',
            field=django_jalali.db.models.jDateTimeField(null=True, verbose_name='تاریخ تحویل'),
        ),
    ]
