# Generated by Django 3.0.8 on 2020-07-16 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_task_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='delivery_date',
        ),
    ]
