# Generated by Django 3.0.8 on 2020-07-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_remove_task_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='multiChange',
            field=models.BooleanField(default=False),
        ),
    ]
