# Generated by Django 3.0.8 on 2020-07-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_auto_20200717_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='isDone',
            new_name='is_done',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='multiChange',
            new_name='multi_change',
        ),
    ]
